spring:
  application:
    name: Spring-FTP-Server-Example

  datasource:
    url: jdbc:h2:mem:ftp
    username: sa
    password:

  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true